/* eslint-disable prettier/prettier */
export const products = [
  {
    name: 'Starter Backpack',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573963/POS/Starter%20Backpack.jpg',
    price: 29.99,
    stock: 50,
    description: 'A simple starter backpack for every adventurer.',
  },
  {
    name: 'Warrior Shield',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573962/POS/Warrior%20Shield.jpg',
    price: 89.5,
    stock: 20,
    description: 'Heavy shield for maximum protection in battle.',
  },
  {
    name: 'Magic Wand',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573962/POS/Magic%20Wand.jpg',
    price: 120,
    stock: 15,
    description: 'Casts powerful spells. Suitable for mage class.',
  },
  {
    name: 'Healing Potion',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573962/POS/Healing%20Potion.jpg',
    price: 9.5,
    stock: 200,
    description: 'Restores 50 HP instantly.',
  },
  {
    name: 'Leather Boots',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573963/POS/Leather%20Boots.jpg',
    price: 45.0,
    stock: 35,
    description: 'Increases movement speed by 10%.',
  },
  {
    name: 'Iron Sword',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748574473/POS/Iron%20Sword.jpg',
    price: 75,
    stock: 25,
    description: 'Reliable melee weapon with decent damage.',
  },
  {
    name: 'Archer’s Bow',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573961/POS/Archer%E2%80%99s%20Bow.jpg',
    price: 85,
    stock: 18,
    description: 'Perfect for long-range attacks.',
  },
  {
    name: 'Explorer’s Map',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573962/POS/Explorer%E2%80%99s%20Map.jpg',
    price: 15,
    stock: 100,
    description: 'Shows hidden locations and treasures.',
  },
  {
    name: 'Fire Scroll',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573960/POS/Fire%20Scroll.jpg',
    price: 60,
    stock: 40,
    description: 'Deals fire damage to all nearby enemies.',
  },
  {
    name: 'Gemstone Ring',
    imageUrl: 'https://res.cloudinary.com/dzcsuttfu/image/upload/v1748573960/POS/Gemstone%20Ring.jpg',
    price: 150,
    stock: 5,
    description: 'Increases magic power by 20%.',
  },
];
